[[permission]]
identifier = "music"
description = "Music folder access."
commands.allow = [
    "read_file",
    "exists",
    "sync_lib",
    "get_all_playlists",
    "get_all_songs",
    "create_playlist"
]

[[scope.allow]]
my-scope = "$HOME/Music/*"

