[[permission]]
identifier = "music"
description = "Music folder access."
commands.allow = [
    "read_file",
    "exists",
    "sync_lib",
    "get_all_playlists",
    "get_all_songs",
    "get_playlist_songs",
    "get_all_starred",
    "create_playlist",
    "add_song_to_playlist",
    "remove_song_from_playlist",
    "remove_playlist",
    "add_is_starred",
    "remove_is_starred"
]

[[scope.allow]]
my-scope = "$HOME/Music/*"

